/**
 * Post-build script: wraps the OpenNext-generated worker.js with our
 * custom routing (OAuthProvider, DOs, WebSocket relay).
 *
 * Run after `npx @opennextjs/cloudflare build`.
 */

import { renameSync, writeFileSync, existsSync } from "fs";

const OPEN_NEXT_DIR = ".open-next";
const WORKER_PATH = `${OPEN_NEXT_DIR}/worker.js`;
const HANDLER_PATH = `${OPEN_NEXT_DIR}/next-handler.js`;

if (!existsSync(WORKER_PATH)) {
  console.error(`Error: ${WORKER_PATH} not found. Run OpenNext build first.`);
  process.exit(1);
}

// 1. Rename the generated worker → next-handler
renameSync(WORKER_PATH, HANDLER_PATH);

// 2. Write a new worker.js that composes our routing with the Next.js handler
writeFileSync(
  WORKER_PATH,
  `// Auto-generated by scripts/wrap-worker.mjs — do not edit manually.
// Composes OpenNext (Next.js) with OAuthProvider + Durable Objects.

// Re-export OpenNext DOs (may be unused but avoids wrangler warnings)
export { DOQueueHandler } from "./next-handler.js";
export { DOShardedTagCache } from "./next-handler.js";
export { BucketCachePurge } from "./next-handler.js";

// Export our custom Durable Objects for wrangler bindings
export { RelayMCP, RelayRoom, DeploymentChainDO } from "../src/index.ts";

// Import the Next.js handler and our routing factory
import nextHandler from "./next-handler.js";
import { createFetchHandler } from "../src/index.ts";

const handler = createFetchHandler(nextHandler);

export default {
  fetch: handler,
};
`,
);

console.log("✓ Worker wrapped: .open-next/worker.js now includes custom routing + DOs");
