/**
 * kaption-mcp-remote — Cloud MCP Relay for WhatsApp
 *
 * Worker routing logic. Exported as a factory function that takes
 * the OpenNext handler and returns the composed fetch handler.
 *
 * The actual entry point is .open-next/worker.js (generated by build:worker),
 * which calls createFetchHandler(nextHandler) with the Next.js handler.
 *
 * Routing:
 * - /sse, /mcp, /token → OAuthProvider (token-protected MCP)
 * - /ws/ext → RelayRoom DO (WebSocket, auth handshake)
 * - /transparency/* → DeploymentChainDO
 * - Everything else → OpenNext (Next.js pages + API routes)
 *
 * Security:
 * - [M3] HMAC-signs oauthReqInfo for /authorize GET
 * - [H1] Sanitized error responses
 * - [L4] x-request-id propagation
 */

import OAuthProvider from "@cloudflare/workers-oauth-provider";
import { Hono } from "hono";
import { RelayMCP } from "./relay-mcp";
import { RelayRoom } from "./relay-room";
import { DeploymentChainDO } from "./deployment-chain";
import { hmacSign } from "./otp";
import type { Env } from "./types";

// Re-export Durable Objects so the wrapper can re-export them for wrangler
export { RelayMCP, RelayRoom, DeploymentChainDO };

// ─── MCP Handlers (authenticated tool calls) ────────────────────────
// Pass directly to OAuthProvider as apiHandlers so ctx.props (set by
// the OAuthProvider after token validation) flows through correctly.
const sseHandler = RelayMCP.serveSSE("/sse");
const mcpHandler = RelayMCP.serve("/mcp");

// ─── Non-OAuth routes ─────────────────────────────────────────────────

const outerApp = new Hono<{ Bindings: Env }>();

// [H6] WebSocket endpoint — token validated via auth handshake in RelayRoom
outerApp.get("/ws/ext", async (c) => {
  const upgradeHeader = c.req.header("Upgrade");
  if (upgradeHeader !== "websocket") {
    return c.text("Expected WebSocket upgrade", 426);
  }

  const url = new URL(c.req.url);

  // Support ?phone= (legacy), ?token= (cloud bridge client), and ?jwt= (JWT auth)
  let phoneHint = url.searchParams.get("phone");
  const token = url.searchParams.get("token");
  const jwt = url.searchParams.get("jwt");

  if (!phoneHint && jwt) {
    // Extract phone from JWT payload for routing (full validation happens in RelayRoom)
    const { extractPhoneFromJwt } = await import("./otp");
    phoneHint = extractPhoneFromJwt(jwt);
    if (!phoneHint) {
      return c.text("Invalid JWT: cannot extract phone", 400);
    }
  }

  if (!phoneHint && token) {
    // Look up phone from extension session token in KV
    const { validateExtensionSession } = await import("./otp");
    const phone = await validateExtensionSession(c.env.OAUTH_KV, token);
    if (!phone) {
      return c.text("Invalid or expired token", 401);
    }
    phoneHint = phone;
  }

  if (!phoneHint) {
    return c.text("Missing phone, token, or jwt parameter", 400);
  }

  // Route to the RelayRoom for this phone number via fetch (not RPC)
  // to properly handle WebSocket upgrade across DO boundary
  const roomId = c.env.RELAY_ROOM.idFromName(phoneHint);
  const room = c.env.RELAY_ROOM.get(roomId);
  return room.fetch(c.req.raw);
});

// Transparency endpoints

// Enrich chain entries with a public Rekor URL for easy verification
function withRekorUrl<T extends { event: { rekorLogIndex: string } }>(entry: T): T & { rekorUrl?: string } {
  const idx = entry.event.rekorLogIndex;
  return idx && idx !== "unknown"
    ? { ...entry, rekorUrl: `https://search.sigstore.dev/?logIndex=${idx}` }
    : entry;
}

outerApp.get("/transparency", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const limit = Math.min(parseInt(c.req.query("limit") || "100", 10), 100);
  const offset = Math.max(parseInt(c.req.query("offset") || "0", 10), 0);
  const history = await chain.getHistory(limit, offset);
  return c.json({ ...history, entries: history.entries.map(withRekorUrl) });
});

outerApp.get("/transparency/latest", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const latest = await chain.getLatest();
  return c.json(latest ? withRekorUrl(latest) : { message: "No deployments recorded" });
});

outerApp.get("/transparency/verify", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const result = await chain.verifyChain();
  return c.json(result);
});

outerApp.get("/transparency/gaps", async (c) => {
  const cfToken = c.req.header("Authorization")?.replace("Bearer ", "");
  const accountId = c.req.query("account_id");

  if (!cfToken || !accountId) {
    return c.json(
      { error: "Provide Authorization: Bearer <CF_TOKEN> and ?account_id=<ID>" },
      400,
    );
  }

  // Fetch CF deployment history
  const cfRes = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/mcp-remote/deployments`,
    { headers: { Authorization: `Bearer ${cfToken}` } },
  );
  if (!cfRes.ok) {
    return c.json({ error: "Failed to fetch CF deployments", status: cfRes.status }, 502);
  }
  const cfData = (await cfRes.json()) as {
    result?: { deployments?: { id: string; created_on: string; source?: string }[] };
  };
  const cfDeployments = cfData.result?.deployments ?? [];

  // Load chain entries
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const { entries } = await chain.getHistory(100, 0);

  const attestedIds = new Set(entries.filter(e => e.event.cfVersionId).map(e => e.event.cfVersionId));
  const firstAttested = entries.find(e => e.event.cfVersionId);
  const cutoff = firstAttested?.event.deployedAt;

  const gaps = cfDeployments.filter(d => {
    if (attestedIds.has(d.id)) return false;
    if (cutoff && d.created_on <= cutoff) return false; // pre-attestation era
    return true;
  });

  return c.json({
    cfVersions: cfDeployments.length,
    chainEntries: entries.length,
    attestedVersions: attestedIds.size,
    gaps: gaps.map(d => ({ id: d.id, created_on: d.created_on, source: d.source })),
    clean: gaps.length === 0,
  });
});

outerApp.post("/transparency/append", async (c) => {
  const apiKey = c.req.header("Authorization")?.replace("Bearer ", "");
  if (!c.env.DEPLOY_API_KEY || apiKey !== c.env.DEPLOY_API_KEY) {
    return c.json({ error: "Unauthorized" }, 401);
  }

  const event = await c.req.json();
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const result = await chain.appendDeployment(event as any);
  return c.json(result);
});

// ─── Factory: create the composed fetch handler ───────────────────────

interface WorkerHandler {
  fetch(request: Request, env: any, ctx: any): Promise<Response>;
}

export function createFetchHandler(nextHandler: WorkerHandler) {
  return async function fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);

    // [L4] Propagate request ID
    const requestId =
      request.headers.get("x-request-id") || crypto.randomUUID();

    // Routes that bypass OAuth entirely
    if (url.pathname === "/ws/ext") {
      return outerApp.fetch(request, env, ctx);
    }
    if (url.pathname.startsWith("/transparency")) {
      return outerApp.fetch(request, env, ctx);
    }
    // Store phone hint by IP for pre-filling the authorize form.
    // The /sse?phone=X request comes from the CLI; /authorize opens in the
    // browser on the same machine → same IP.  Short TTL, harmless if stale.
    if (url.pathname === "/sse" && url.searchParams.has("phone")) {
      const ip = request.headers.get("cf-connecting-ip") || "unknown";
      const phone = url.searchParams.get("phone")!;
      ctx.waitUntil(
        env.OAUTH_KV.put(`login_hint:${ip}`, phone, { expirationTtl: 300 }),
      );
    }

    // OAuthProvider handles:
    // - /sse, /mcp → apiHandlers (OAuth token-protected MCP)
    // - /token → token exchange
    // - /register → RFC 7591 dynamic client registration
    // - Everything else → defaultHandler (Next.js)
    const oauthHandler = new OAuthProvider({
      apiHandlers: {
        "/sse": sseHandler as any,
        "/mcp": mcpHandler as any,
      },
      authorizeEndpoint: "/authorize",
      tokenEndpoint: "/token",
      // Advertise registration endpoint in /.well-known/oauth-authorization-server
      // so MCP clients (Claude Code, Cursor, etc.) can auto-register
      clientRegistrationEndpoint: "/register",
      defaultHandler: {
        async fetch(
          req: Request,
          oauthEnv: Env,
          c: ExecutionContext,
        ): Promise<Response> {
          const reqUrl = new URL(req.url);

          // [M3] For /authorize GET, HMAC-sign the oauthReqInfo before passing to Next.js
          // env.OAUTH_PROVIDER (OAuthHelpers) is available here inside defaultHandler
          let finalReq = req;
          if (reqUrl.pathname === "/authorize" && req.method === "GET") {
            try {
              const oauthReqInfo =
                await oauthEnv.OAUTH_PROVIDER.parseAuthRequest(req);
              if (!oauthReqInfo.clientId) {
                return new Response("Invalid authorization request", {
                  status: 400,
                });
              }
              const encoded = btoa(JSON.stringify(oauthReqInfo));
              const signed = await hmacSign(encoded, env.INTERNAL_API_KEY);
              const newUrl = new URL(req.url);
              newUrl.searchParams.set("_oauthReqInfo", signed);

              // Look up phone hint stored by /sse?phone= (same IP)
              const ip = req.headers.get("cf-connecting-ip") || "unknown";
              const phoneHint = await env.OAUTH_KV.get(`login_hint:${ip}`);
              if (phoneHint) {
                newUrl.searchParams.set("_loginHint", phoneHint);
              }

              finalReq = new Request(newUrl.toString(), req);
            } catch {
              return new Response(
                "Invalid authorization request. Register your MCP client first via POST /register.",
                { status: 400 },
              );
            }
          }

          const response = await nextHandler.fetch(finalReq, oauthEnv, c);
          // [L4] Add request ID to response
          const newResponse = new Response(response.body, response);
          newResponse.headers.set("x-request-id", requestId);
          return newResponse;
        },
      } as any,
    });

    return oauthHandler.fetch(request, env, ctx);
  };
}
