/**
 * kaption-mcp-remote — Cloud MCP Relay for WhatsApp
 *
 * Worker routing logic. Exported as a factory function that takes
 * the OpenNext handler and returns the composed fetch handler.
 *
 * The actual entry point is .open-next/worker.js (generated by build:worker),
 * which calls createFetchHandler(nextHandler) with the Next.js handler.
 *
 * Routing:
 * - /sse, /mcp, /token → OAuthProvider (token-protected MCP)
 * - /ws/ext → RelayRoom DO (WebSocket, auth handshake)
 * - /transparency/* → DeploymentChainDO
 * - Everything else → OpenNext (Next.js pages + API routes)
 *
 * Security:
 * - [M3] HMAC-signs oauthReqInfo for /authorize GET
 * - [H1] Sanitized error responses
 * - [L4] x-request-id propagation
 */

import OAuthProvider, { getOAuthApi, type OAuthProviderOptions } from "@cloudflare/workers-oauth-provider";
import { Hono } from "hono";
import {
  connectionLifetimeCallback,
  disconnect,
  handleTokenRequest,
  listConnections,
} from "./connection-lifetime";
import { RelayMCP } from "./relay-mcp";
import { RelayRoom, ROOM_ACCOUNT_HEADER } from "./relay-room";
import { DeploymentChainDO } from "./deployment-chain";
import {
  decryptLoginHint,
  deriveAccountRef,
  encryptLoginHint,
  hmacSign,
  validateExtensionSession,
  validateJwt,
} from "./otp";
import type { Env } from "./types";
import {
  connectDeps,
  pollConnectPairing,
  startAllowed,
  startConnectPairing,
} from "./connect-code";

// Re-export Durable Objects so the wrapper can re-export them for wrangler
export { RelayMCP, RelayRoom, DeploymentChainDO };

// ─── MCP Handlers (authenticated tool calls) ────────────────────────
// Pass directly to OAuthProvider as apiHandlers so ctx.props (set by
// the OAuthProvider after token validation) flows through correctly.
const sseHandler = RelayMCP.serveSSE("/sse");
const mcpHandler = RelayMCP.serve("/mcp");

// ─── Non-OAuth routes ─────────────────────────────────────────────────

const outerApp = new Hono<{ Bindings: Env }>();

const MCP_ORIGIN = "https://mcp.kaptionai.com";
const LEGACY_MCP_ORIGIN = "https://mcp-ext.kaptionai.com";
const MCP_ORIGINS = new Set([MCP_ORIGIN, LEGACY_MCP_ORIGIN]);
const OPENAI_CHALLENGE_PATH = "/.well-known/openai-apps-challenge";

/**
 * Keep OAuth discovery bound to the hostname the client actually selected.
 * Both production domains reach the same worker, but RFC 9728 clients compare
 * the advertised protected resource with the URL they connected to. Unknown
 * worker/dev hosts deliberately fall back to the canonical production origin
 * rather than becoming attacker-controlled OAuth issuers through Host spoofing.
 */
export function getMcpOrigin(requestUrl: URL): string {
  return MCP_ORIGINS.has(requestUrl.origin) ? requestUrl.origin : MCP_ORIGIN;
}

// OpenAI provides the token during portal domain verification. Keeping it in
// an environment secret lets the well-known endpoint return exactly one token
// without a deploy or a repository-stored credential.
outerApp.get(OPENAI_CHALLENGE_PATH, (c) => {
  const token = c.env.OPENAI_APPS_CHALLENGE_TOKEN?.trim();
  if (!token) return c.text("Not configured", 404);
  return c.text(token, 200, { "Cache-Control": "no-store" });
});

// CORS preflight for /ws/auth — needed for Chrome extension fetch (no host_permissions)
outerApp.options("/ws/auth", (c) => {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Authorization, Content-Type",
      "Access-Control-Max-Age": "86400",
    },
  });
});

// mcp.CLOUD_RELAY.3 — JWT→wstoken exchange, 60s single-use KV TTL
outerApp.post("/ws/auth", async (c) => {
  try {
    const auth = c.req.header("Authorization");
    if (!auth?.startsWith("Bearer ")) {
      return c.json({ error: "invalid_request", error_description: "Missing bearer token" }, 401);
    }
    const jwt = auth.slice(7);

    // Validate JWT and extract phone → accountRef
    const phone = await validateJwt(c.env.JWT_SECRET, jwt);
    if (!phone) {
      return c.json({ error: "invalid_token", error_description: "Invalid JWT" }, 401);
    }
    const accountRef = await deriveAccountRef(phone, c.env.PHONE_REF_SECRET);
    if (!accountRef) {
      return c.json({ error: "invalid_token", error_description: "Invalid JWT" }, 401);
    }

    // Generate single-use token, store in KV with a 60 s TTL
    const token = crypto.randomUUID();
    await c.env.OAUTH_KV.put(`ws-auth:${token}`, accountRef, { expirationTtl: 60 });

    return c.json({ token }, 200, { "Access-Control-Allow-Origin": "*" });
  } catch (e: any) {
    console.error("[ws/auth] Token exchange error:", e?.message || e);
    return c.json({ error: "server_error", error_description: "Internal error" }, 500);
  }
});

// [H6] WebSocket endpoint — token validated via auth handshake in RelayRoom
outerApp.get("/ws/ext", async (c) => {
  const upgradeHeader = c.req.header("Upgrade");
  if (upgradeHeader !== "websocket") {
    return c.json({ error: "invalid_request", error_description: "Expected WebSocket upgrade" }, 426);
  }

  const url = new URL(c.req.url);

  // Support ?wstoken= (short-lived, preferred), ?phone= (legacy), ?token= (extension session), ?jwt= (JWT auth)
  let accountRefHint: string | null = null;
  const wstoken = url.searchParams.get("wstoken");
  const phoneHint = url.searchParams.get("phone");
  const token = url.searchParams.get("token");
  const jwt = url.searchParams.get("jwt");

  // Preferred: short-lived single-use token from POST /ws/auth
  if (wstoken) {
    const ref = await c.env.OAUTH_KV.get(`ws-auth:${wstoken}`);
    if (!ref) {
      return c.json({ error: "invalid_token", error_description: "Invalid or expired wstoken" }, 401);
    }
    accountRefHint = ref;
    // Single-use: delete immediately
    c.executionCtx.waitUntil(c.env.OAUTH_KV.delete(`ws-auth:${wstoken}`));
  }

  if (!accountRefHint && phoneHint) {
    accountRefHint = await deriveAccountRef(phoneHint, c.env.PHONE_REF_SECRET);
  }

  if (!accountRefHint && jwt) {
    // mcp.CLOUD_RELAY.14 — the JWT's signature is checked here too, not only its payload read.
    const jwtPhone = await validateJwt(c.env.JWT_SECRET, jwt);
    if (!jwtPhone) {
      return c.json({ error: "invalid_token", error_description: "Invalid JWT" }, 401);
    }
    accountRefHint = await deriveAccountRef(jwtPhone, c.env.PHONE_REF_SECRET);
  }

  if (!accountRefHint && token) {
    const session = await validateExtensionSession(
      c.env.OAUTH_KV,
      token,
      c.env.EPHEMERAL_STATE_SECRET,
    );
    if (!session) {
      return c.json({ error: "invalid_token", error_description: "Invalid or expired token" }, 401);
    }
    accountRefHint = session.accountRef;
  }

  if (!accountRefHint) {
    return c.json({ error: "invalid_request", error_description: "Missing phone, token, jwt, or wstoken parameter" }, 400);
  }

  // Route to the RelayRoom for this account reference via fetch (not RPC)
  // to properly handle WebSocket upgrade across DO boundary
  const roomId = c.env.RELAY_ROOM.idFromName(accountRefHint);
  const room = c.env.RELAY_ROOM.get(roomId);
  // mcp.CLOUD_RELAY.14 — the room learns whose it is from us, never from the client (any value it sent is replaced):
  // the handshake then only counts for that account.
  const forwarded = new Request(c.req.raw);
  forwarded.headers.set(ROOM_ACCOUNT_HEADER, accountRefHint);
  return room.fetch(forwarded);
});

// mcp.CLOUD_RELAY.12 — the extension's "Connected apps" list: the AI apps
// connected to this WhatsApp account, and a way to disconnect one. The
// extension calls these from its service worker with its Kaption JWT.
const CONNECTIONS_CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Authorization",
  "Access-Control-Max-Age": "86400",
};

async function accountFromBearer(authorization: string | undefined, env: Env): Promise<string | null> {
  if (!authorization?.startsWith("Bearer ")) return null;
  const phone = await validateJwt(env.JWT_SECRET, authorization.slice(7));
  if (!phone) return null;
  return deriveAccountRef(phone, env.PHONE_REF_SECRET);
}

// getOAuthApi needs the provider's options but never serves pages itself.
const HELPERS_ONLY_HANDLER = { fetch: async () => new Response("Not found", { status: 404 }) };

function oauthApi(env: Env) {
  return getOAuthApi(buildOAuthOptions(MCP_ORIGIN, HELPERS_ONLY_HANDLER), env);
}

// mcp.CONNECT_CODE.1-2 — "Add to Claude": the extension asks for a connect code. Its JWT names the phone (and keeps
// strangers from spending our API calls); the proof is the WhatsApp handshake the extension then sends.
const CONNECT_CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Authorization, Content-Type",
  "Access-Control-Max-Age": "86400",
};

outerApp.options("/ext/connect-code/start", () => new Response(null, { status: 204, headers: CONNECT_CORS }));
outerApp.options("/ext/connect-code/status", () => new Response(null, { status: 204, headers: CONNECT_CORS }));

outerApp.post("/ext/connect-code/start", async (c) => {
  const auth = c.req.header("Authorization");
  const phone = auth?.startsWith("Bearer ") ? await validateJwt(c.env.JWT_SECRET, auth.slice(7)) : null;
  if (!phone) return c.json({ error: "invalid_token" }, 401, CONNECT_CORS);
  const accountRef = await deriveAccountRef(phone, c.env.PHONE_REF_SECRET);
  if (!accountRef || !(await startAllowed(c.env.OAUTH_KV, accountRef))) {
    return c.json({ error: "rate_limited" }, 429, CONNECT_CORS);
  }
  try {
    const started = await startConnectPairing(connectDeps(c.env), phone);
    if (!started) return c.json({ error: "handshake_unavailable" }, 502, CONNECT_CORS);
    return c.json(started, 200, CONNECT_CORS);
  } catch (e: any) {
    console.error("[connect-code] start failed:", e?.message || e);
    return c.json({ error: "server_error" }, 500, CONNECT_CORS);
  }
});

outerApp.post("/ext/connect-code/status", async (c) => {
  const auth = c.req.header("Authorization");
  const phone = auth?.startsWith("Bearer ") ? await validateJwt(c.env.JWT_SECRET, auth.slice(7)) : null;
  if (!phone) return c.json({ error: "invalid_token" }, 401, CONNECT_CORS);
  let body: { pairId?: unknown } = {};
  try { body = await c.req.json(); } catch { body = {}; }
  try {
    const status = await pollConnectPairing(connectDeps(c.env), String(body.pairId ?? ""), phone);
    return c.json(status, 200, CONNECT_CORS);
  } catch (e: any) {
    console.error("[connect-code] status failed:", e?.message || e);
    return c.json({ status: "error" }, 500, CONNECT_CORS);
  }
});

outerApp.options("/ext/connections", () => new Response(null, { status: 204, headers: CONNECTIONS_CORS }));
outerApp.options("/ext/connections/:grantId", () => new Response(null, { status: 204, headers: CONNECTIONS_CORS }));

outerApp.get("/ext/connections", async (c) => {
  const userId = await accountFromBearer(c.req.header("Authorization"), c.env);
  if (!userId) return c.json({ error: "Unauthorized" }, 401, CONNECTIONS_CORS);
  try {
    const connections = await listConnections(oauthApi(c.env), c.env.OAUTH_KV, userId);
    return c.json({ connections }, 200, { ...CONNECTIONS_CORS, "Cache-Control": "no-store" });
  } catch (e: any) {
    console.error("[connections] list failed:", e?.message || e);
    return c.json({ error: "Could not load connections" }, 500, CONNECTIONS_CORS);
  }
});

outerApp.delete("/ext/connections/:grantId", async (c) => {
  const userId = await accountFromBearer(c.req.header("Authorization"), c.env);
  if (!userId) return c.json({ error: "Unauthorized" }, 401, CONNECTIONS_CORS);
  const grantId = c.req.param("grantId");
  if (!/^[^\s:/]{1,256}$/.test(grantId)) return c.json({ error: "Invalid connection id" }, 400, CONNECTIONS_CORS);
  try {
    // revokeGrant is scoped to this account's own grants.
    await disconnect(oauthApi(c.env), c.env.OAUTH_KV, userId, grantId);
    return c.json({ ok: true }, 200, CONNECTIONS_CORS);
  } catch (e: any) {
    console.error("[connections] disconnect failed:", e?.message || e);
    return c.json({ error: "Could not disconnect" }, 500, CONNECTIONS_CORS);
  }
});

// Transparency endpoints

// Enrich chain entries with a public Rekor URL for easy verification
function withRekorUrl<T extends { event: { rekorLogIndex: string } }>(entry: T): T & { rekorUrl?: string } {
  const idx = entry.event.rekorLogIndex;
  return idx && idx !== "unknown"
    ? { ...entry, rekorUrl: `https://search.sigstore.dev/?logIndex=${idx}` }
    : entry;
}

outerApp.get("/transparency", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const limit = Math.min(parseInt(c.req.query("limit") || "100", 10), 100);
  const offset = Math.max(parseInt(c.req.query("offset") || "0", 10), 0);
  const history = await chain.getHistory(limit, offset);
  return c.json({ ...history, entries: history.entries.map(withRekorUrl) });
});

outerApp.get("/transparency/latest", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const latest = await chain.getLatest();
  return c.json(latest ? withRekorUrl(latest) : { message: "No deployments recorded" });
});

outerApp.get("/transparency/verify", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const result = await chain.verifyChain();
  return c.json(result);
});

outerApp.get("/transparency/gaps", async (c) => {
  const cfToken = c.req.header("Authorization")?.replace("Bearer ", "");
  const accountId = c.req.query("account_id");

  if (!cfToken || !accountId) {
    return c.json(
      { error: "Provide Authorization: Bearer <CF_TOKEN> and ?account_id=<ID>" },
      400,
    );
  }

  // Guard against path/SSRF injection before interpolating into the CF API URL —
  // Cloudflare account IDs are exactly 32 lowercase hex characters.
  if (!/^[0-9a-f]{32}$/.test(accountId)) {
    return c.json({ error: "Invalid account_id (expected 32 hex characters)" }, 400);
  }

  // Fetch CF deployment history
  const cfRes = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/workers/scripts/mcp-remote/deployments`,
    { headers: { Authorization: `Bearer ${cfToken}` } },
  );
  if (!cfRes.ok) {
    return c.json({ error: "Failed to fetch CF deployments", status: cfRes.status }, 502);
  }
  const cfData = (await cfRes.json()) as {
    result?: { deployments?: { id: string; created_on: string; source?: string }[] };
  };
  const cfDeployments = cfData.result?.deployments ?? [];

  // Load chain entries
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const { entries } = await chain.getHistory(100, 0);

  const attestedIds = new Set(entries.filter(e => e.event.cfVersionId).map(e => e.event.cfVersionId));
  const firstAttested = entries.find(e => e.event.cfVersionId);
  const cutoff = firstAttested?.event.deployedAt;

  const gaps = cfDeployments.filter(d => {
    if (attestedIds.has(d.id)) return false;
    if (cutoff && d.created_on <= cutoff) return false; // pre-attestation era
    return true;
  });

  return c.json({
    cfVersions: cfDeployments.length,
    chainEntries: entries.length,
    attestedVersions: attestedIds.size,
    gaps: gaps.map(d => ({ id: d.id, created_on: d.created_on, source: d.source })),
    clean: gaps.length === 0,
  });
});

outerApp.post("/transparency/append", async (c) => {
  const apiKey = c.req.header("Authorization")?.replace("Bearer ", "");
  if (!c.env.DEPLOY_API_KEY || apiKey !== c.env.DEPLOY_API_KEY) {
    return c.json({ error: "Unauthorized" }, 401);
  }

  const event = await c.req.json();
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const result = await chain.appendDeployment(event as any);
  return c.json(result);
});

// ─── Bearer challenges as JSON ────────────────────────────────────────

/**
 * The OAuth library answers a request without a token with an empty 401 body
 * and a bad token with `{error, error_description}`. Some MCP clients and
 * registries read the body rather than the header, so every Bearer 401 gets
 * an RFC 6750-style JSON body that also names the RFC 9728 metadata URL.
 * The status and every header — above all `WWW-Authenticate` — pass through
 * untouched; only the body and Content-Type change.
 */
export async function toJsonBearerChallenge(response: Response, requestUrl: URL): Promise<Response> {
  if (response.status !== 401) return response;
  const challenge = response.headers.get("WWW-Authenticate");
  if (!challenge || !/^Bearer\b/i.test(challenge)) return response;

  const resourceMetadata =
    /resource_metadata="([^"]+)"/.exec(challenge)?.[1]
    ?? `${getMcpOrigin(requestUrl)}/.well-known/oauth-protected-resource${requestUrl.pathname}`;
  const challengeError = /\berror="([^"]+)"/.exec(challenge)?.[1];

  let upstream: { error?: unknown; error_description?: unknown } = {};
  try {
    const text = await response.text();
    if (text) upstream = JSON.parse(text);
  } catch {
    // Not JSON — fall back to what the challenge says.
  }

  const error =
    typeof upstream.error === "string" ? upstream.error : challengeError ?? "invalid_request";
  const errorDescription =
    typeof upstream.error_description === "string" && upstream.error_description
      ? upstream.error_description
      : error === "invalid_token"
        ? "The access token is invalid or expired"
        : "Missing bearer token. Authorize via OAuth using the resource metadata URL.";

  const headers = new Headers(response.headers);
  headers.set("Content-Type", "application/json");
  headers.delete("Content-Length");
  return new Response(
    JSON.stringify({ error, error_description: errorDescription, resource_metadata: resourceMetadata }),
    { status: 401, statusText: response.statusText, headers },
  );
}

// ─── Factory: create the composed fetch handler ───────────────────────

interface WorkerHandler {
  fetch(request: Request, env: any, ctx: any): Promise<Response>;
}

/**
 * Security headers for responses served through the Next handler.
 *
 * These used to live in next.config.mjs as a `headers()` rule matching every
 * route, but such a rule is unrepresentable across this stack's two
 * path-to-regexp versions: Next 15.5's config validator rejects the v8 wildcard
 * '/*path' ("Unexpected MODIFIER"), while @opennextjs/cloudflare's
 * routingHandler runs path-to-regexp v8, which rejects the classic '/(.*)'
 * ("Unexpected ("). The v6 form '/:path*' fails under v8 too. Leaving '/(.*)'
 * in place made the router throw on EVERY dynamic request, so the whole site
 * returned 500 while static assets still served.
 *
 * Applying them here removes route matching from the equation entirely.
 */
export function applySecurityHeaders(headers: Headers): void {
  headers.set("X-Content-Type-Options", "nosniff");
  headers.set("X-Frame-Options", "DENY");
  headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  headers.set(
    "Content-Security-Policy",
    "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; "
      + "style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; "
      + "connect-src 'self' https://mcp.kaptionai.com https://mcp-ext.kaptionai.com",
  );
}

/**
 * OAuthProvider options — shared by the Worker and by the helpers that list
 * and revoke connections, because getOAuthApi needs the very same options.
 */
export function buildOAuthOptions(mcpOrigin: string, defaultHandler: unknown): OAuthProviderOptions<Env> {
  return {
    apiHandlers: {
      "/sse": sseHandler as any,
      "/mcp": mcpHandler as any,
    },
    authorizeEndpoint: "/authorize",
    tokenEndpoint: "/token",
    // Advertise registration endpoint in /.well-known/oauth-authorization-server
    // so MCP clients (Claude Code, Cursor, etc.) can auto-register
    clientRegistrationEndpoint: "/register",
    // Pin OAuth grants and access-token audiences to the trusted MCP hostname
    // the client selected. The provider also serves RFC 9728 metadata and
    // advertises it in 401 challenges for both the origin-level and
    // path-specific well-known URL.
    scopesSupported: ["kaption:access"],
    resourceMetadata: {
      resource: `${mcpOrigin}/mcp`,
      authorization_servers: [mcpOrigin],
      scopes_supported: ["kaption:access"],
      bearer_methods_supported: ["header"],
      resource_name: "Kaption AI",
    },
    // mcp.CLOUD_RELAY.9/10 — each connection lasts as long as the person chose
    // on the consent page. The library enforces only the fixed one-year choice
    // (a per-connection refreshTokenTTL set at the first token exchange);
    // "90 days without use" and "until I disconnect it" are open-ended here and
    // policed by connection-lifetime.ts. The library's own defaults — a refresh
    // token dying 30 days after connecting however much it was used, and a
    // client registration dying at 90 — are what forced people to reconnect.
    refreshTokenTTL: undefined,
    clientRegistrationTTL: undefined,
    tokenExchangeCallback: connectionLifetimeCallback,
    defaultHandler: defaultHandler as any,
  } as OAuthProviderOptions<Env>;
}

export function createFetchHandler(nextHandler: WorkerHandler) {
  return async function fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    const mcpOrigin = getMcpOrigin(url);

    // [L4] Propagate request ID
    const requestId =
      request.headers.get("x-request-id") || crypto.randomUUID();

    // Public standards and domain-verification routes bypass OAuth.
    if (url.pathname === OPENAI_CHALLENGE_PATH) {
      return outerApp.fetch(request, env, ctx);
    }

    // Routes that bypass OAuth entirely
    if (url.pathname === "/ws/ext" || url.pathname === "/ws/auth") {
      return outerApp.fetch(request, env, ctx);
    }
    if (url.pathname.startsWith("/transparency")) {
      return outerApp.fetch(request, env, ctx);
    }
    if (url.pathname === "/ext/connections" || url.pathname.startsWith("/ext/connections/")) {
      return outerApp.fetch(request, env, ctx);
    }
    if (url.pathname.startsWith("/ext/connect-code/")) {
      return outerApp.fetch(request, env, ctx);
    }
    // Store phone hint by IP for pre-filling the authorize form.
    // The /sse?phone=X request comes from the CLI; /authorize opens in the
    // browser on the same machine → same IP.  Short TTL, harmless if stale.
    if (url.pathname === "/sse" && url.searchParams.has("phone")) {
      const ip = request.headers.get("cf-connecting-ip") || "unknown";
      const phone = url.searchParams.get("phone")!;
      ctx.waitUntil((async () => {
        const encryptedHint = await encryptLoginHint(phone, env.EPHEMERAL_STATE_SECRET);
        if (!encryptedHint) return;
        await env.OAUTH_KV.put(`login_hint:${ip}`, encryptedHint, { expirationTtl: 300 });
      })());
    }

    // OAuthProvider handles:
    // - /sse, /mcp → apiHandlers (OAuth token-protected MCP)
    // - /token → token exchange
    // - /register → RFC 7591 dynamic client registration
    // - Everything else → defaultHandler (Next.js)
    // mcp.CLOUD_RELAY.1 — OAuth 2.1 discovery, register, token endpoints
    // mcp.AUTH.2 — OAuthProvider validates bearer on every /sse + /mcp request
    const oauthOptions = buildOAuthOptions(mcpOrigin, {
      async fetch(
        req: Request,
        oauthEnv: Env,
        c: ExecutionContext,
      ): Promise<Response> {
        const reqUrl = new URL(req.url);

        // mcp.CLOUD_RELAY.2 — OTP phone flow; HMAC-signed oauthReqInfo
        // env.OAUTH_PROVIDER (OAuthHelpers) is available here inside defaultHandler
        let finalReq = req;
        if (reqUrl.pathname === "/authorize" && req.method === "GET") {
          try {
            const oauthReqInfo =
              await oauthEnv.OAUTH_PROVIDER.parseAuthRequest(req);
            if (!oauthReqInfo.clientId) {
              return new Response("Invalid authorization request", {
                status: 400,
              });
            }
            const encoded = btoa(JSON.stringify(oauthReqInfo));
            const signed = await hmacSign(encoded, env.INTERNAL_API_KEY);
            const newUrl = new URL(req.url);
            newUrl.searchParams.set("_oauthReqInfo", signed);

            // Look up phone hint stored by /sse?phone= (same IP)
            const ip = req.headers.get("cf-connecting-ip") || "unknown";
            const encryptedHint = await env.OAUTH_KV.get(`login_hint:${ip}`);
            if (encryptedHint) {
              c.waitUntil(env.OAUTH_KV.delete(`login_hint:${ip}`));
              const phoneHint = await decryptLoginHint(
                encryptedHint,
                env.EPHEMERAL_STATE_SECRET,
              );
              if (phoneHint) {
                newUrl.searchParams.set("_loginHint", phoneHint);
              }
            }

            finalReq = new Request(newUrl.toString(), req);
          } catch (error) {
            // People see this page inside Claude or ChatGPT, so it says what to
            // do; the library's reason goes to the logs (wrangler tail).
            console.warn(
              "[authorize] sign-in request rejected:",
              error instanceof Error ? error.message : error,
            );
            return new Response(
              "Kaption couldn't start signing in to this app. Remove Kaption from the app's connectors, add it again, and try once more.",
              { status: 400, headers: { "Content-Type": "text/plain; charset=utf-8" } },
            );
          }
        }

        const response = await nextHandler.fetch(finalReq, oauthEnv, c);
        // [L4] Add request ID to response
        const newResponse = new Response(response.body, response);
        newResponse.headers.set("x-request-id", requestId);
        applySecurityHeaders(newResponse.headers);
        return newResponse;
      },
    });
    const oauthHandler = new OAuthProvider(oauthOptions);

    // The library caches its helpers on `env.OAUTH_PROVIDER` the first time a
    // request reaches the default handler, and the Worker's env object is
    // shared by every request an isolate serves. Our options differ by hostname
    // (each advertises its own resource), so helpers cached by a request on one
    // hostname rejected the other's sign-ins whenever the app sent its RFC 8707
    // `resource` — Claude and ChatGPT do — as invalid_target, shown as the
    // "Invalid authorization request" page, depending on which hostname the
    // isolate happened to serve first. Each request gets its own env, with
    // helpers built from its own options.
    const requestEnv: Env = { ...env };
    requestEnv.OAUTH_PROVIDER = getOAuthApi(oauthOptions, requestEnv);

    // mcp.CLOUD_RELAY.10/11 — connection lifetimes are enforced around the
    // token endpoint (connection-lifetime.ts).
    if (url.pathname === "/token" && request.method === "POST") {
      return handleTokenRequest(
        request,
        requestEnv,
        ctx,
        (req) => oauthHandler.fetch(req, requestEnv, ctx),
        () => requestEnv.OAUTH_PROVIDER,
      );
    }

    return toJsonBearerChallenge(await oauthHandler.fetch(request, requestEnv, ctx), url);
  };
}
