/**
 * kaption-mcp-remote — Cloud MCP Relay for WhatsApp
 *
 * Worker routing logic. Exported as a factory function that takes
 * the OpenNext handler and returns the composed fetch handler.
 *
 * The actual entry point is .open-next/worker.js (generated by build:worker),
 * which calls createFetchHandler(nextHandler) with the Next.js handler.
 *
 * Routing:
 * - /sse, /mcp, /token → OAuthProvider (token-protected MCP)
 * - /ws/ext → RelayRoom DO (WebSocket, auth handshake)
 * - /transparency/* → DeploymentChainDO
 * - Everything else → OpenNext (Next.js pages + API routes)
 *
 * Security:
 * - [M3] HMAC-signs oauthReqInfo for /authorize GET
 * - [H1] Sanitized error responses
 * - [L4] x-request-id propagation
 */

import OAuthProvider from "@cloudflare/workers-oauth-provider";
import { Hono } from "hono";
import { RelayMCP } from "./relay-mcp";
import { RelayRoom } from "./relay-room";
import { DeploymentChainDO } from "./deployment-chain";
import { hmacSign } from "./otp";
import type { Env } from "./types";

// Re-export Durable Objects so the wrapper can re-export them for wrangler
export { RelayMCP, RelayRoom, DeploymentChainDO };

// ─── MCP Handler (authenticated tool calls) ───────────────────────────

const mcpApp = new Hono<{ Bindings: Env }>();

mcpApp.all("/sse", async (c) => {
  try {
    const handler = RelayMCP.serveSSE("/sse");
    return await handler.fetch(c.req.raw, c.env, c.executionCtx);
  } catch (error) {
    // [H1] Never leak internal details
    console.error("[mcp] SSE handler error");
    return c.text("Internal Server Error", 500);
  }
});

mcpApp.all("/mcp", async (c) => {
  try {
    const handler = RelayMCP.serve("/mcp");
    return await handler.fetch(c.req.raw, c.env, c.executionCtx);
  } catch (error) {
    console.error("[mcp] MCP handler error");
    return c.text("Internal Server Error", 500);
  }
});

// ─── Non-OAuth routes ─────────────────────────────────────────────────

const outerApp = new Hono<{ Bindings: Env }>();

// [H6] WebSocket endpoint — token validated via auth handshake in RelayRoom
outerApp.get("/ws/ext", async (c) => {
  const upgradeHeader = c.req.header("Upgrade");
  if (upgradeHeader !== "websocket") {
    return c.text("Expected WebSocket upgrade", 426);
  }

  // Extract phone hint from query (used for room routing only, not auth)
  // Actual authentication happens via the auth handshake message in RelayRoom
  const url = new URL(c.req.url);
  const phoneHint = url.searchParams.get("phone");
  if (!phoneHint) {
    return c.text("Missing phone parameter", 400);
  }

  // Route to the RelayRoom for this phone number
  const roomId = c.env.RELAY_ROOM.idFromName(phoneHint);
  const room = c.env.RELAY_ROOM.get(roomId);
  return room.handleExtensionWebSocket(c.req.raw);
});

// Transparency endpoints
outerApp.get("/transparency", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const limit = Math.min(parseInt(c.req.query("limit") || "100", 10), 100);
  const offset = Math.max(parseInt(c.req.query("offset") || "0", 10), 0);
  const history = await chain.getHistory(limit, offset);
  return c.json(history);
});

outerApp.get("/transparency/latest", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const latest = await chain.getLatest();
  return c.json(latest || { message: "No deployments recorded" });
});

outerApp.get("/transparency/verify", async (c) => {
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const result = await chain.verifyChain();
  return c.json(result);
});

outerApp.post("/transparency/append", async (c) => {
  const apiKey = c.req.header("Authorization")?.replace("Bearer ", "");
  if (!c.env.DEPLOY_API_KEY || apiKey !== c.env.DEPLOY_API_KEY) {
    return c.json({ error: "Unauthorized" }, 401);
  }

  const event = await c.req.json();
  const chainId = c.env.DEPLOYMENT_CHAIN.idFromName("main");
  const chain = c.env.DEPLOYMENT_CHAIN.get(chainId);
  const result = await chain.appendDeployment(event as any);
  return c.json(result);
});

// ─── Factory: create the composed fetch handler ───────────────────────

interface WorkerHandler {
  fetch(request: Request, env: any, ctx: any): Promise<Response>;
}

export function createFetchHandler(nextHandler: WorkerHandler) {
  return async function fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);

    // [L4] Propagate request ID
    const requestId =
      request.headers.get("x-request-id") || crypto.randomUUID();

    // Routes that bypass OAuth entirely
    if (url.pathname === "/ws/ext") {
      return outerApp.fetch(request, env, ctx);
    }
    if (url.pathname.startsWith("/transparency")) {
      return outerApp.fetch(request, env, ctx);
    }

    // OAuthProvider handles:
    // - /sse, /mcp → apiHandlers (OAuth token-protected MCP)
    // - /token → token exchange
    // - /register → RFC 7591 dynamic client registration
    // - Everything else → defaultHandler (Next.js)
    const oauthHandler = new OAuthProvider({
      apiHandlers: {
        "/sse": mcpApp as any,
        "/mcp": mcpApp as any,
      },
      authorizeEndpoint: "/authorize",
      tokenEndpoint: "/token",
      // Advertise registration endpoint in /.well-known/oauth-authorization-server
      // so MCP clients (Claude Code, Cursor, etc.) can auto-register
      clientRegistrationEndpoint: "/register",
      defaultHandler: {
        async fetch(
          req: Request,
          oauthEnv: Env,
          c: ExecutionContext,
        ): Promise<Response> {
          const reqUrl = new URL(req.url);

          // [M3] For /authorize GET, HMAC-sign the oauthReqInfo before passing to Next.js
          // env.OAUTH_PROVIDER (OAuthHelpers) is available here inside defaultHandler
          let finalReq = req;
          if (reqUrl.pathname === "/authorize" && req.method === "GET") {
            try {
              const oauthReqInfo =
                await oauthEnv.OAUTH_PROVIDER.parseAuthRequest(req);
              if (!oauthReqInfo.clientId) {
                return new Response("Invalid authorization request", {
                  status: 400,
                });
              }
              const encoded = btoa(JSON.stringify(oauthReqInfo));
              const signed = await hmacSign(encoded, env.INTERNAL_API_KEY);
              const newUrl = new URL(req.url);
              newUrl.searchParams.set("_oauthReqInfo", signed);
              finalReq = new Request(newUrl.toString(), req);
            } catch {
              return new Response(
                "Invalid authorization request. Register your MCP client first via POST /register.",
                { status: 400 },
              );
            }
          }

          const response = await nextHandler.fetch(finalReq, oauthEnv, c);
          // [L4] Add request ID to response
          const newResponse = new Response(response.body, response);
          newResponse.headers.set("x-request-id", requestId);
          return newResponse;
        },
      } as any,
    });

    return oauthHandler.fetch(request, env, ctx);
  };
}
